# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Closets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('total_retail_value', models.CharField(max_length=48)),
                ('total_resale_value', models.CharField(max_length=48)),
                ('total_profit', models.CharField(max_length=48)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sneakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FilePathField()),
                ('brand', models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Jordan', 'Jordan'), ('Vans', 'Vans')], default='Nike', max_length=15)),
                ('release_date', models.DateTimeField()),
                ('purchase_date', models.DateTimeField(verbose_name='date purchased')),
                ('retail_price', models.CharField(max_length=15)),
                ('resale_value', models.CharField(max_length=15)),
                ('closet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneakers', to='deadstox.Closets')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneakers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
