# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deadstox', '0004_sneakers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closets',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sneakers', to=settings.AUTH_USER_MODEL),
        ),
    ]
