# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadstox', '0005_auto_20160916_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='purchase_date',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='release_date',
            field=models.CharField(max_length=15),
        ),
    ]
