# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deadstox', '0006_auto_20160921_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closets',
            name='total_profit',
        ),
        migrations.RemoveField(
            model_name='closets',
            name='total_resale_value',
        ),
        migrations.RemoveField(
            model_name='closets',
            name='total_retail_value',
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='closet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sneakers', to='deadstox.Closets'),
        ),
    ]
