# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadstox', '0008_auto_20160921_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='images',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
