# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadstox', '0009_auto_20160922_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='resale_value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
